[Setup]
; device mac
Name = XXXXXXXXX
 device serial
Serial = XXXXXXX
; model
Model = BD4A8S4P
; update interval
Interval = 5
; 100% soc detection voltage - use 0.1 less the absorbtion voltage
SocDetectionVoltage = 14.1
; Capacity in Ah
BatteryCapacity = 50
; Low soc alarm set
LowSocAlarmSet = 30
; Low soc alarm clear
LowSocAlarmClear = 50
; debug
debug = false

